### ISSUE TITLE
Cogen[TestsDefinitions.T1.Tree] crashes

### ISSUE THREAD

**Issue by torgeirsh** [alexarchambault/scalacheck-shapeless#54] opened 2017-01-18 09:47 UTC
I noticed that ArbitraryTests has a test for Arbitrary[T1.Tree], but there's no similar test in CogenTests. I tried to add one at CogenTests.scala:146, but the expression Cogen[T1.Tree] crashes:

    java.lang.StackOverflowError
        at shapeless.Lazy$$anon$1.value$lzycompute(lazy.scala:121)
        at shapeless.Lazy$$anon$1.value(lazy.scala:121)
        at org.scalacheck.derive.DerivedInstances$class.derivedCogen(Instances.scala:122)
        at org.scalacheck.Shapeless$.derivedCogen(Shapeless.scala:5)
        at org.scalacheck.CogenTests$$anonfun$13$$anonfun$apply$14$anon$derivedCogen$macro$330$1.inst$macro$313$lzycompute(CogenTests.scala:146)
        at org.scalacheck.CogenTests$$anonfun$13$$anonfun$apply$14$anon$derivedCogen$macro$330$1.inst$macro$313(CogenTests.scala:146)
        at org.scalacheck.CogenTests$$anonfun$13$$anonfun$apply$14$anon$derivedCogen$macro$330$1.inst$macro$306$lzycompute(CogenTests.scala:146)
        at org.scalacheck.CogenTests$$anonfun$13$$anonfun$apply$14$anon$derivedCogen$macro$330$1.inst$macro$306(CogenTests.scala:146)
        at org.scalacheck.CogenTests$$anonfun$13$$anonfun$apply$14$anon$derivedCogen$macro$330$1$$anonfun$inst$macro$304$1.apply(CogenTests.scala:146)
        at org.scalacheck.CogenTests$$anonfun$13$$anonfun$apply$14$anon$derivedCogen$macro$330$1$$anonfun$inst$macro$304$1.apply(CogenTests.scala:146)
        at shapeless.Lazy$$anon$1.value$lzycompute(lazy.scala:121)
        at shapeless.Lazy$$anon$1.value(lazy.scala:121)
        at org.scalacheck.derive.MkCogen$$anonfun$genericCoproduct$1.apply(MkCogen.scala:42)
        at org.scalacheck.derive.MkCogen$$anonfun$genericCoproduct$1.apply(MkCogen.scala:42)
        at org.scalacheck.derive.MkCogen$$anon$1.cogen(MkCogen.scala:27)
        at org.scalacheck.derive.DerivedInstances$class.derivedCogen(Instances.scala:122)
        at org.scalacheck.Shapeless$.derivedCogen(Shapeless.scala:5)
        at org.scalacheck.CogenTests$$anonfun$13$$anonfun$apply$14$anon$derivedCogen$macro$330$1.inst$macro$321$lzycompute(CogenTests.scala:146)
        at org.scalacheck.CogenTests$$anonfun$13$$anonfun$apply$14$anon$derivedCogen$macro$330$1.inst$macro$321(CogenTests.scala:146)
        at org.scalacheck.CogenTests$$anonfun$13$$anonfun$apply$14$anon$derivedCogen$macro$330$1.inst$macro$320$lzycompute(CogenTests.scala:146)
        at org.scalacheck.CogenTests$$anonfun$13$$anonfun$apply$14$anon$derivedCogen$macro$330$1.inst$macro$320(CogenTests.scala:146)
        at org.scalacheck.CogenTests$$anonfun$13$$anonfun$apply$14$anon$derivedCogen$macro$330$1$$anonfun$inst$macro$315$1.apply(CogenTests.scala:146)
        at org.scalacheck.CogenTests$$anonfun$13$$anonfun$apply$14$anon$derivedCogen$macro$330$1$$anonfun$inst$macro$315$1.apply(CogenTests.scala:146)
        at shapeless.Lazy$$anon$1.value$lzycompute(lazy.scala:121)
        at shapeless.Lazy$$anon$1.value(lazy.scala:121)
    [... and so on]

**Comment by joroKr21** [comment] 2017-05-05 08:59
That's to be expected since [`MkHListCogen`](https://github.com/alexarchambault/scalacheck-shapeless/blob/master/core/shared/src/main/scala/org/scalacheck/derive/MkCogen.scala#L63) and [`MkCoproductCogen`](https://github.com/alexarchambault/scalacheck-shapeless/blob/master/core/shared/src/main/scala/org/scalacheck/derive/MkCogen.scala#L91) are `Strict` in the head. I don't know if this is intended, because sometimes special care is needed to deal with recursive types (e.g. `Gen.lzy`). But you can try to use `Lazy` and see what happens.

**Comment by torgeirsh** [comment] 2017-08-09 09:35
Changing the head to Lazy makes the expression Cogen[T1.Tree] compile successfully, but I don't know if the generated value is correct. Would be great if someone who is familiar with the internals could take a look.

**Comment by joroKr21** [comment] 2017-09-03 05:36
Actually the generic `Repr` implicits are already wrapped in `Lazy` [here](https://github.com/alexarchambault/scalacheck-shapeless/blob/master/core/shared/src/main/scala/org/scalacheck/derive/MkCogen.scala#L30-L43). So support for recursive types is intended. I think the issue is that calling `contramap` in the implementation forces evaluation too early. Replacing it with this seems to work:
```scala
instance(Cogen { (seed: Seed, p: P) =>
  cogen.value.cogen.perturb(seed, gen.to(p))
})
```

Note how `cogen.value.cogen` is not forced until the `perturb` function is actually called. Would you like to make a PR with this fix and the added test with `T1.Tree`?

**Comment by joroKr21** [comment] 2017-09-04 02:48
I forgot auto closing doesn't work from comments. This is fixed now.

**Comment by alexarchambault** [comment] 2017-09-04 11:49
Should be fixed in master, yep. I'll do a release once https://github.com/alexarchambault/scalacheck-shapeless/pull/73 and https://github.com/alexarchambault/scalacheck-shapeless/pull/74 are settled.

**Closed by alexarchambault** 2017-09-04 11:49 UTC
